### ISSUE TITLE
SWIFT_VERSION '5.0' is unsupported

### ISSUE THREAD

**Issue by mjpieters** [Lutzifer/homebrew-tap#2]
On macOS High Sierra (10.13.6), brew can't compile the project:

```
==> xcodebuild
Last 15 lines from /Users/mj/Library/Logs/Homebrew/keyboardswitcher/01.xcodebuild:
2019-11-26 13:16:29 +0000

xcodebuild

note: Using new build system
note: Planning build
note: Constructing build description
Build system information
error: SWIFT_VERSION '5.0' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'keyboardSwitcher')

** BUILD FAILED **


If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/lutzifer/homebrew-tap/issues
```

**Comment by mjpieters** [comment]
Given https://github.com/Lutzifer/keyboardSwitcher/commit/ad51cd8d4a98b08ad4cd9a1dc97ddf92cfaf5047, it seems a small test needs to be added to see what swift versions are available on the current system.

OTOH, I need to upgrade this system to a more recent macOS..

**Comment by Lutzifer** [comment]
Hi and thanks for posting the issue.

I will only have the newest version of the code available via homebrew, which targets the newest available xcode.

You can install older versions that are compatible by building the sources yourself though.
